
# get http://localhost:8888/api/v1/sounds?orderby=desc:<fields1>,<fields2>,<fields3>;asc:<field>,<field>&filterfield=<field>:<value>;<field>:<value>;<field>:<alue>&likefield=<field>:<like>&limit=10
# query params:
# 
# orderby = desc(<fields1>,<fields2>,<fields3>),asc()
# filterfield = (<field>:<value>,<field>:<value>,<field>:<alue>....)
# likefield = "(<field>:<like>,...)"
# limit = 10

get http://localhost:8888/api/v1/sounds?filterfield=id:9;

get http://localhost:8888/api/v1/sounds?filterfield=id:like(A%);

get http://localhost:8888/api/v1/sounds?filterfield=id:1-2;

get http://localhost:8888/api/v1/sounds?filterfield=id:2-;

get http://localhost:8888/api/v1/sounds?filterfield=id:-2

get http://localhost:8888/api/v1/sounds?filterfield=id:-2|name:like(a%)

//get http://localhost:8888/api/v1/sound/10

//delete http://localhost:8888/api/v1/sound/2

# put http://localhost:8888/api/v1/sound/0
# Content-Type: application/json

# {
#     "name": "Рыцарь славы",
#     "text": "Ты затмеваешь солнца свет...",
#     "reit": 5
# }

###
post http://localhost:8888/api/v1/user
Content-Type: application/json

{
    "first_name": "Alex Gladkiy"
}