
@base_url = http://localhost:8888
@version = api/v1

### Create new user
post {{base_url}}/{{version}}/user
Content-Type: application/json

{
    "Login": "AlexG",
    "Email": "sane4ek2002@gmail.com",
    "Phone": "+79604492320",
    "First_Name": "Alexandr",
    "Middle_Name": "Petrovich",
    "Last_Name": "Gladkiy",
    "Status": 0
}
