
@base_url = http://localhost:8888
@version = api/v1

### Create new user
post {{base_url}}/{{version}}/user
Content-Type: application/json

{
    "login": "AlexG",
    "email": "sane4ek2002@gmail.com",
    "phone": "+79604492320",
    "firstName": "Alexandr",
    "middleName": "Petrovich",
    "lastName": "Gladkiy",
    "status": 0
}

### Get user list
get {{base_url}}/{{version}}/users
Content-Type: application/json